Metrics/LineLength:
  Max: 350
Metrics/BlockLength:
  Max: 550
Metrics/MethodLength:
  Max: 60
Metrics/ClassLength:
  Max: 200
Metrics/AbcSize:
  Max: 80
Metrics/CyclomaticComplexity:
  Max: 25
Metrics/PerceivedComplexity:
  Max: 20
Style/NumericLiterals:
  Enabled: false